### ISSUE TITLE
CLI for shifting time of mock ETOs

### ISSUE THREAD

**Issue by rudolfix** [Neufund/platform-contracts#312]
**Why we do it**
We have several under-tested ETO state transition cases that were already an visible on production and are quite hard to add as an permanent fixtures. In essence we want to e2e and manually test following cases
* Setup to Pre-Sale transition
* Pre-Sale to Sale transition
* Sale to Signing transition
On top of that we will be able to manually see what happens on Signing -> Refund transition which we only do in unit tests now.
The intention is for QA to be able to mock internal time of the ETO in a way that they can see such transitions. Same for e2e which is automated on CircleCI and uses private backend/contracts deployments.

**What need to be implemented**
Implement a CLI in platform contracts repo, similar to `deployETO.js` or `inspectETO.js` that when run via `truffle` will mock internal state of ETO to simulate state transitions.

**Technical Details**

On dev networks we deploy `MockETOCommitment` contract instead `ETOCommitment` Mock contract, among other things, allows to mock internal timestamps of ETO state machine (See `_mockShiftBackTime`). Look for method usage in existing code.
For reference please read
https://github.com/Neufund/platform-backend/wiki/5.06.-Use-Case-Investment - ETO State machine reference
https://github.com/Neufund/platform-contracts/wiki/Smart-Contracts-Catalogue#platformterms-etoterms-durationterms-and-shareholderrights - a kind of primer on ETO Contracts

**Acceptance Criteria**
* [ ] a CLI that shifts time of ETO to the next state transition - delta in seconds passed as parameter
* [ ] CLI should accept eto commitment address or a link to public profile for example https://platform.neufund.io/api/eto-listing/eto/view/c48e8968-d2fd-4e86-9845-26328feef243 (see `deployETO`)
* [ ] should not allow to go over state transition to previous state (delta must be validated)
* [ ] should provide user friendly errors for most common cases (eto does not exist, eto does not have start date etc.)
• should have a function does time shifting separate so it's easily copied to e2e tests in frontend repo (you can talk to @Moejoe90 or @desfero on how it works)

**Testing**
Manual testing would be enough, you can also unit test shiftting function if it's not yet...

**Deployment**
* [ ] please explain to QA how to use CLI and provide some examples
* [ ] please explain frontend team how to shift time in e2e tests

**Comment by djudjuu** [comment]
## UPDATE:

in conversation with FE and backend, we figured the most appropriate solution will be to offer this as a service over an api-endpoint. this will enable e2e tests for the frontend.

Also, we could just write the shift into a soldity function, that way it will be easier tested by the backend-unit tests (i do not understand why yet)

**Comment by djudjuu** [comment]
here are my notes on solving this task:

===========


# Table of Contents

1.  [TASK1: CLI for ETO Tests](#org3f4831f)
    1.  [read issue descriptions](#orgc84229b)
    2.  [what states does an ETO go through? -> 7, see IETOCommitmentStates.sol](#orgb07b15f)
    3.  [how to know when next state transition will happen?](#org0b15b04)
    4.  [where to compute by how much to shift? Solidity > JS](#org4579bc0)
    5.  [put it on its own branch](#org223ebd9)
    6.  [which repo to work in ??](#orga864df7)
        1.  [work in backend repo](#org6b5006a)
    7.  [in contract repo](#orge0832d6)
        1.  [understand how to query state](#orge9e7841)
        2.  [write basic truffle test](#org15ec6f5)
        3.  [write js-script to be invoked by cmdLine](#orgab557f2)
        4.  [example says signing to refund&#x2026; how to manipulate the contract so that it goes that way?](#org1621143)
        5.  [BUG:SOLVED shifting to state after public with \_mockPastTime causes errors](#org4583f34)
        6.  [implement function in commandline-tool](#org36d2177)
    8.  [backend repo:](#orgdc2de52)
        1.  [adjust the script to work via an exposed api](#orgfa2d838)
        2.  [test pipeline](#org824ea1d)
        3.  [learn python blockchain :](#org328e38c)
    9.  [run script via an API endpoint](#org9785972)
        1.  [define api-endpoint in backend/](#orge286fde)
    10. [wrap api in a service](#orgdc34d47)
    11. [define error-classes](#org8e80af7)
    12. [Write helper to fetch address from fixture name STALLED](#orgd7e8da1)
    13. [write tests for service -> does not need to be done,](#org6f1ee0c)
    14. [NOT DONE readup on git submodules > some other time](#org88f95da)
    15. [add test for eto not in universe](#org3c24ded)
        1.  [helper notes](#orgdb531ad)
    16. [implement helper function on contract directly](#org7bf388b)
        1.  [STOPPED move contract implementation to backend-repo so that I can deploy the new MockEto contract -> increase GAS LIMIT on parity node](#org526eb5e)
        2.  [increase gasLimit of parity-node](#orgc9f6a51)
        3.  [what are all the networks in truffle.js](#orgc279811)
    17. [create gaslimit raising prs](#org1eaf7b8)
    18. [move script implementation to backend-repo -> STOPPED](#org9e11d3b)
    19. [DO a JS implementation to be used by frontend-devs STUCK](#org0cbd0a7)
    20. [test it by looking at deployed frontend (build frontend notes)](#org5f18cc7)
    21. [change endpoint to use the newly created helper on contract](#org74403aa)
        1.  [use updated contracts in backend-repo:](#org792661e)
    22. [test pipeline](#orge9b21f9)
    23. [WHERE AM I NOW?](#org0d17770)
    24. [show merged PR to Moe, learn together with Nicole how to use it](#orgdcdbe06)
        1.  [test whether invalid args return helpful messages](#org8f9b7ed)
    25. [PRS to be merged:](#org1408b44)


<a id="org3f4831f"></a>

# DONE TASK1: CLI for ETO Tests


<a id="orgc84229b"></a>

## TODO read issue descriptions


<a id="orgb07b15f"></a>

## DONE what states does an ETO go through? -> 7, see IETOCommitmentStates.sol

ETOState.
  Setup
  Whitelist
  Public
  Signing
  Refund
  Payout


<a id="org0b15b04"></a>

## DONE how to know when next state transition will happen?

-   check array ETO<sub>STATE</sub><sub>DURATIONS</sub>, which is filled in constructor by ETOTerms


<a id="org4579bc0"></a>

## DONE where to compute by how much to shift? Solidity > JS

-   DECISION: should the computation how much time should be shifted be
    implemented in js or in the smart contract itself?
    -   JS: my instinct would be to put it in js, as the SC should have only the
        minimal computations needed
    -   SOLIDITY: the python tests could use it too, without having to reimplement it (said Dave)

=> for now, implemented in solidity, using startOfInternal
js would use startOfStates

> trouble as ETOCOmmitment is pretty big&#x2026;


<a id="org223ebd9"></a>

## DONE put it on its own branch


<a id="orga864df7"></a>

## DONE which repo to work in ??


<a id="org6b5006a"></a>

### work in backend repo


<a id="orge0832d6"></a>

## in contract repo


<a id="orge9e7841"></a>

### DONE understand how to query state

some tests use CommitmentState.js, whcih abstracts to 4 states vs the 7 defined in ETOStat
whcih f to use to understand ETO state?
there are various CommitmentState-enums defined, I need to use the one in \`\`helpers/CommitmentState.js\`\`
-> expectLogStateTransition


<a id="org15ec6f5"></a>

### DONE write basic truffle test

    yarn build
    then run individual test
yarn truffle test &#x2013;network inprocess<sub>test</sub> test/ETO/ETOCommitment.js test/setup.js

does not compile, run solc on it first

1.  extra test here:

        it("should move time to right before state transition", async () => {
    await deployETO({ ovrArtifact: MockETOCommitment });
    const timestamp = await latestTimestamp();
    durTable = defaultDurationTable();
    startDate = new web3.BigNumber(timestamp + 2 \* dayInSeconds);
    const whitelistD = durTable[CommitmentState.Whitelist].add(1);
    // set start data to 2 days from now via mocker
    const startTx = await etoCommitment.<sub>mockStartDate</sub>(
      etoTerms.address,
      equityToken.address,
      startDate,
      startDate.add(whitelistD),
      { from: company },
    );
    expectLogETOStartDateSet(startTx, company, 0, startDate.add(whitelistD));
    
    // move to right before startDate via helper and wait
    await etoCommitment.<sub>shiftToBeforeNextState</sub>(10);
    await increaseTime(15);
    const tx = await etoCommitment.handleStateTransitions();
    expectLogStateTransition(tx, CommitmentState.Setup, CommitmentState.Whitelist, "ignore");
    
      // do so again for whitelist->public transition
      await etoCommitment.<sub>shiftToBeforeNextState</sub>(10);
      await increaseTime(15);
      const tx2 = await etoCommitment.handleStateTransitions();
      expectLogStateTransition(tx2, CommitmentState.Whitelist, CommitmentState.Public, "ignore" );
    });


<a id="orgab557f2"></a>

### DONE write js-script to be invoked by cmdLine

-   model upon inspectETO.js which is used like this:
    
    \`\`\`yarn truffle exec scripts/verifyDeployment.js &#x2013;network localhost &#x2013;universe 0x762db45f0ef6c83d64181988195991ef115dc2b3\`\`\`

-   ?! what does the "exec" option do? -> tells it that it is to be executed?


<a id="org1621143"></a>

### TODO example says signing to refund&#x2026; how to manipulate the contract so that it goes that way?

-   i need to understand all the phases of the ETO 
    > check <https://github.com/Neufund/platform-backend/wiki/5.06.-Use-Case-Investment>


<a id="org4583f34"></a>

### DONE BUG:SOLVED shifting to state after public with \_mockPastTime causes errors

-> shift all states so that one can not cause illogical states where a previous state ends before the next one


<a id="org36d2177"></a>

### DONE implement function in commandline-tool

-   build in checks for address existence and startDate, plus errormgs
-   see how to call the commandline


<a id="orgdc2de52"></a>

## backend repo:

-   contains contract repo, but can not run as it does not know truffle


<a id="orgfa2d838"></a>

### adjust the script to work via an exposed api

always use make down before doing things


<a id="org824ea1d"></a>

### test pipeline

-   make down
-   fire up minimal services: test-unit-services-up
-   check ext-services here
    <http://localhost:1337/ui/#!/e2e-tests/api_e2etests_eto_time_travel>

-   restart ext-services with wihtout downing everything

make update-service service=dev<sub>external</sub><sub>services</sub><sub>mock</sub><sub>api</sub>

use docker ps to get id
docker kill id

navigate to /dev<sub>external</sub><sub>mock</sub><sub>api</sub>
and start manually python run<sub>api.py</sub>

-   get ETO addresses from
    -> make run output (best save that to file to browse later)
    -   fixtures defined in eto<sub>fixtures.json</sub> => ERROR: saying contract with address 0xc3Cce192d9Dae80245cce3bDE1B35c4230949abD is not deployed\\"",

"type": "platform<sub>contracts.exceptions.PlatformContractsContractNotDeployed</sub>"


<a id="org328e38c"></a>

### TODO learn python blockchain :

check py3 docs
full instance 4 transactions vs instance (call only)
method().transact()
method().call()


<a id="org9785972"></a>

## DONE run script via an API endpoint


<a id="orge286fde"></a>

### define api-endpoint in backend/

yaml and in e2etests.py


<a id="orgdc34d47"></a>

## DONE wrap api in a service


<a id="org8e80af7"></a>

## DONE define error-classes


<a id="orgd7e8da1"></a>

## Write helper to fetch address from fixture name STALLED


<a id="org6f1ee0c"></a>

## DONE write tests for service -> does not need to be done,

for this specific endpoint, we need no tests as it will be tested by the frontend implicitly

   in general:
make test im richtigen verzeichnis
   make test in root => all


<a id="org88f95da"></a>

## NOT DONE readup on git submodules > some other time


<a id="org3c24ded"></a>

## DONE add test for eto not in universe

where to get interface from?
Tomek send me a bunch of useful links to helper on slack:


<a id="orgdb531ad"></a>

### helper notes

or maybe like this function get<sub>eto</sub><sub>fixture</sub><sub>address</sub> from platform<sub>testing</sub>/platform<sub>contracts.py</sub> in platform common (edited) 
￼￼
70m3k￼ 1:25 PM
def obtain<sub>eto</sub><sub>terms</sub><sub>contract</sub>(eto<sub>id</sub>: str) -> ConciseContract:
    connector = NeufundContractsConnector(ethereum<sub>service</sub><sub>configuration</sub>)
    neufund<sub>contracts</sub> = connector.get<sub>neufund</sub><sub>contracts</sub>()
    commitment<sub>artifact</sub> = neufund<sub>contracts.resolve</sub><sub>artifact</sub><sub>from</sub><sub>interface</sub>("commitmentInterface", eto<sub>id</sub>)
    eto<sub>contract</sub> = neufund<sub>contracts.get</sub><sub>instance</sub>(commitment<sub>artifact</sub>, eto<sub>id</sub>)
    eto<sub>terms</sub><sub>address</sub> = eto<sub>contract.etoTerms</sub>()
    terms<sub>artifact</sub> = neufund<sub>contracts.resolve</sub><sub>artifact</sub><sub>from</sub><sub>interface</sub>("termsInterface", eto<sub>terms</sub><sub>address</sub>)
    return neufund<sub>contracts.get</sub><sub>instance</sub>(terms<sub>artifact</sub>, eto<sub>terms</sub><sub>address</sub>)
new messages
1:27 PM
again from py<sub>platform</sub><sub>common</sub> now file  platform<sub>testing</sub>/utils/ethereum<sub>helpers.py</sub> there is get<sub>eto</sub><sub>contract</sub> function with eto<sub>address</sub> as parameter (edited) 
1:28 PM
and snippet I've sent you earlier could rewritten using get<sub>eto</sub><sub>contract</sub> function ￼


<a id="org7bf388b"></a>

## DONE implement helper function on contract directly


<a id="org526eb5e"></a>

### STOPPED move contract implementation to backend-repo so that I can deploy the new MockEto contract -> increase GAS LIMIT on parity node

-   ERROR: Deploying it
    -   Deploying MockETOCommitment
        &#x2026; 0x3640d1909d08919c9331c4120ff00bf4306569870fc13e3127995ec2b696ca54
-   TODO move all work there

?? how to increase gas-limit used in migrations? why does it work in the truffle test, but not in the backend-fixture deployment?


<a id="orgc9f6a51"></a>

### DONE increase gasLimit of parity-node

-   there are two places in parity repo
    nfconf.json
    supervisor.conf
-   one more place in contract repo, when starting truffle.js
-   one more in contract repo: testrpc.sh
-   

1.  DONE gas limit check

    parity node vs latest raise
    
    <https://ethgasstation.info/blog/ethereum-block-size/>


<a id="orgc279811"></a>

### DONE what are all the networks in truffle.js

LEARNED:

-   localhost deployed on local machine / ganache
-   inprocess: also
-   nf<sub>private</sub>: ? >  dev environment that is deployed every night
-   nf<sub>private</sub><sub>io</sub>: ? >  dev environment that is deployed every night
-   coverage: used for coverage analysis (currenl. not working)
-   forked<sub>live</sub>: running on own nodes
-   forked<sub>nano</sub><sub>live</sub>: ?? -> mainnet
-   live: mainnet
-   console<sub>live</sub>: also mainnet
-   localhost<sub>live</sub>: ?  -> mainnet. test mainnet deployment on localhost (no special permissions, no fixtures)
-   inprocess<sub>test</sub>: ? > DEV stuff
-   localhost<sub>test</sub>: ? > DEV stuff
-   inprocess<sub>massive</sub><sub>test</sub>: > was used to test initial ICBM > out of date
-   

live mirrors mainnet

everything with test can use DEV things


<a id="org1eaf7b8"></a>

## DONE create gaslimit raising prs

on both contracts and parity s
see task "implement helper function on contract directly"


<a id="org9e11d3b"></a>

## DONE move script implementation to backend-repo -> STOPPED

BLOCKED backend repo can not run truffle properly


<a id="org0cbd0a7"></a>

## DONE DO a JS implementation to be used by frontend-devs STUCK

-   STOPPER:
    -   how to get the current time from the chain?
    -   can not use web3 in script?
    -   can not use bigNumber
    -   how

?? why is BigNumber always used via web3?
?? How to get the current time in script? Blocktime does not work out of the box, maybe just use unix timestamp -> ask Moe

-> 


<a id="org5f18cc7"></a>

## DONE test it by looking at deployed frontend (build frontend notes)

-> deploy frontend!

-   install latest yarn (from website)
-   run yarn in repo-root to install dependencies
-   cd into packages/web do > yarn start
-   also do yarn upgrade
-   also yarn deduplicate
-   if backend is runnning locally, look at <https://localhost:9090>


<a id="org74403aa"></a>

## DONE change endpoint to use the newly created helper on contract


<a id="org792661e"></a>

### use updated contracts in backend-repo:

make update-submodules

    make down & make test unit &#x2026; got an error:
    *root*.node-gyp/8.16.2/include/node/v8.h:3370:19: warning: inline function 'void\* v8::Object::GetAlignedPointerFromInternalField(int)' used but never defined
   V8<sub>INLINE</sub> void\* GetAlignedPointerFromInternalField(int index);
                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make: **\*** [scrypt.target.mk:121: Release/obj.target/scrypt/src/node-boilerplate/scrypt<sub>common.o</sub>] Error 1
gyp ERR! build error 
gyp ERR! stack Error: \`make\` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node<sub>modules</sub>/npm/node<sub>modules</sub>/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess.<sub>handle.onexit</sub> (internal/child<sub>process.js</sub>:198:12)
gyp ERR! System Linux 5.0.0-32-generic
gyp ERR! command \\"/usr/local/bin/node\\" \\"/usr/local/lib/node<sub>modules</sub>/npm/node<sub>modules</sub>/node-gyp/bin/node-gyp.js\\" \\"rebuild\\"
gyp ERR! cwd /usr/src/platform-contracts/node<sub>modules</sub>/scrypt
gypmake: Leaving directory '/usr/src/platform-contracts/node<sub>modules</sub>/scrypt/build'
 ERR! node -v v8.16.2
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok"


<a id="orge9b21f9"></a>

## test pipeline

go to backend node at
<http://localhost:1337/ui/#!/e2e-tests/api_e2etests_eto_time_travel>

get deployed contract address from fixture log
make run fixtures


<a id="org0d17770"></a>

## DONE WHERE AM I NOW?

-   waiting to be merged


<a id="orgdcdbe06"></a>

## DONE show merged PR to Moe, learn together with Nicole how to use it


<a id="org8f9b7ed"></a>

### TODO test whether invalid args return helpful messages

nicola uses it via postman


<a id="org1408b44"></a>

## PRS to be merged:

-   DONE parity > increase gas PR#25 DONE
-   DONE contracts > add mocker + tests PR#312, wait for marcin to explain different deployment configs DONE
-   backend > service and api using mocker PR#2276
